apiVersion: v1
kind: Service
metadata:
  name: playground-service
  namespace: dev
spec:
  selector:
    app: playground
  ports:
    - protocol: TCP
      port: 80       # External service port
      targetPort: 8080  # Matches containerPort
  type: ClusterIP 